file_format: "1"
id: nulu
name: NuLu
type: shield
url: https://github.com/Tanuki-2974/zmk-config
requires: [seeeduino_xiao_ble]
features:
  - keys
  - display
  - encoder
  - underglow
  - backlight
  - studio
  - pointer
siblings:
  - NuLu_L
  - NuLu_R